/**
 * SPDX-FileCopyrightText: 2024 Ferdinand Thiessen <opensource@fthiessen.de>
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
import { test } from '../support/fixtures/random-user'
import { expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import {
	captureBoardAuthFromSave,
	createWhiteboard,
	fetchBoardContent,
	openFilesApp,
	openWhiteboardFromFiles,
} from '../support/utils'

const MODAL_DISCLOSURE_TEXT = 'Output is generated by AI. Make sure to always double-check.'
const DIAGRAM_DISCLOSURE_TEXT = 'Diagram shown here is generated by AI. Make sure to always double-check.'
const AI_GENERATED_TYPE = 'assistant-mermaid'
const normalizeText = (text = '') => text.replace(/\s+/g, ' ').trim()

const ensureAssistantBoardReady = async (page: Page, boardName: string) => {
	const assistantButton = page.getByRole('button', { name: 'Assistant', exact: true })

	try {
		await expect(assistantButton).toBeVisible({ timeout: 15000 })
	} catch {
		await openWhiteboardFromFiles(page, boardName)
		await expect(assistantButton).toBeVisible({ timeout: 30000 })
	}

	return assistantButton
}

test.beforeEach(async ({ page }) => {
	let taskIdCounter = 1

	await page.route(
		'**/ocs/v2.php/taskprocessing/schedule',
		async (route) => {
			const taskId = taskIdCounter++
			await route.fulfill({
				status: 200,
				contentType: 'application/json',
				body: JSON.stringify({
					ocs: {
						meta: {
							status: 'ok',
							statuscode: 200,
							message: 'OK',
						},
						data: {
							task: {
								id: taskId,
								type: 'core:text2text',
								status: 'STATUS_RUNNING',
								appId: 'whiteboard',
							},
						},
					},
				}),
			})
		},
	)

	await page.route(
		'**/ocs/v2.php/taskprocessing/task/*',
		(route, request) => {
			const taskId = parseInt(request.url().split('/').pop() || '0', 10) // Extract taskId from URL
			route.fulfill({
				status: 200,
				contentType: 'application/json',
				body: JSON.stringify({
					ocs: {
						meta: {
							status: 'ok',
							statuscode: 200,
							message: 'OK',
						},
						data: {
							task: {
								id: taskId,
								type: 'core:text2text',
								lastUpdated: 1744024462,
								status: 'STATUS_SUCCESSFUL',
								userId: 'admin',
								appId: 'whiteboard',
								input: {
									max_tokens: 1234,
									model: 'model_2',
									input: 'a',
								},
								output: {
									output: `flowchart TD
 A[Christmas] -->|Get money| B(Go shopping)
 B --> C{Let me think}
 C -->|One| D[Laptop]
 C -->|Two| E[iPhone]
 C -->|Three| F[Car]`,
								},
								customId: '',
								completionExpectedAt: 1744024460,
								progress: 1,
								scheduledAt: 1744024459,
								startedAt: 1744024462,
								endedAt: 1744024462,
							},
						},
					},
				}),
			})
		},
	)

	await openFilesApp(page)
})

test('Assistant Button', async ({ page }) => {
	const boardName = `Assistant ${Date.now()}`
	await createWhiteboard(page, { name: boardName })
	const assistantButton = await ensureAssistantBoardReady(page, boardName)
	await assistantButton.click()
	await expect(page.getByText(MODAL_DISCLOSURE_TEXT)).toBeVisible()
	await page.getByRole('textbox', { name: 'Prompt to generate diagram' }).fill('abc')
	const authFromSave = captureBoardAuthFromSave(page)
	await page.getByRole('button', { name: 'Generate' }).click()
	await expect(page.getByRole('textbox', { name: 'Prompt to generate diagram' })).not.toBeVisible()
	const { fileId, jwt } = await authFromSave
	const auth = { fileId, jwt }

	await expect.poll(async () => {
		const content = await fetchBoardContent(page, auth)
		return content.elements.some((element) => normalizeText(element.text) === DIAGRAM_DISCLOSURE_TEXT)
	}, {
		timeout: 30000,
		interval: 500,
	}).toBe(true)

	const content = await fetchBoardContent(page, auth)
	const disclosureElement = content.elements.find((element) => normalizeText(element.text) === DIAGRAM_DISCLOSURE_TEXT)

	expect(disclosureElement).toBeTruthy()
	expect(disclosureElement.customData?.aiDisclosureLabel).toBe(true)
	expect(disclosureElement.customData?.aiGenerated).toBe(AI_GENERATED_TYPE)
	expect(content.elements.length).toBeGreaterThan(0)
	expect(content.elements.every((element) => element.customData?.aiGenerated === AI_GENERATED_TYPE)).toBe(true)
})

test('Restart on false Assistant output', async ({ page }) => {
	await page.route(
		'**/ocs/v2.php/taskprocessing/task/*',
		(route, request) => {
			const taskId = parseInt(request.url().split('/').pop() || '0', 10) // Extract taskId from URL
			route.fulfill({
				status: 200,
				contentType: 'application/json',
				body: JSON.stringify({
					ocs: {
						meta: {
							status: 'ok',
							statuscode: 200,
							message: 'OK',
						},
						data: {
							task: {
								id: taskId,
								type: 'core:text2text',
								lastUpdated: 1744024462,
								status: 'STATUS_SUCCESSFUL',
								userId: 'admin',
								appId: 'whiteboard',
								input: {
									max_tokens: 1234,
									model: 'model_2',
									input: 'a',
								},
								output: {
									output: 'INVALID MERMAID SYNTAX',
								},
								customId: '',
								completionExpectedAt: 1744024460,
								progress: 1,
								scheduledAt: 1744024459,
								startedAt: 1744024462,
								endedAt: 1744024462,
							},
						},
					},
				}),
			})
		},
	)
	const boardName = `Assistant invalid ${Date.now()}`
	await createWhiteboard(page, { name: boardName })
	const assistantButton = await ensureAssistantBoardReady(page, boardName)
	await assistantButton.click()
	await expect(page.getByText(MODAL_DISCLOSURE_TEXT)).toBeVisible()
	await page.getByRole('textbox', { name: 'Prompt to generate diagram' }).fill('abc')
	await page.getByRole('button', { name: 'Generate' }).click()
	await expect(page.getByRole('textbox', { name: 'Prompt to generate diagram' })).toHaveValue('abc')
	await expect(page.getByText(MODAL_DISCLOSURE_TEXT)).toBeVisible()
})
