<!--
  - SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
  - SPDX-License-Identifier: AGPL-3.0-or-later
-->
<script>
import { NcTextField, NcButton, NcModal } from '@nextcloud/vue'
import { t } from '@nextcloud/l10n'
import { ScheduleTask } from '../services/assistant/api'
import { parseMermaidToExcalidraw } from '@excalidraw/mermaid-to-excalidraw'
import { convertToExcalidrawElements, getCommonBounds } from '@nextcloud/excalidraw'
import { defineComponent } from 'vue'

const AI_GENERATED_TYPE = 'assistant-mermaid'
const WHITEBOARD_DEFAULT_FONT_FAMILY = 3
const WHITEBOARD_DEFAULT_FONT = 'Cascadia, monospace'
const AI_DISCLOSURE_LABEL_GAP = 16
const AI_DISCLOSURE_LABEL_FONT_FAMILY = 2
const AI_DISCLOSURE_LABEL_FONT = 'Helvetica, Arial, sans-serif'
const AI_DISCLOSURE_LABEL_FONT_SIZE = 14
const AI_DISCLOSURE_LABEL_MIN_WIDTH = 280
const AI_DISCLOSURE_LABEL_MAX_WIDTH = 440
const AI_DISCLOSURE_LABEL_FONT_STRING = `${AI_DISCLOSURE_LABEL_FONT_SIZE}px ${AI_DISCLOSURE_LABEL_FONT}`

export default defineComponent({
	name: 'AssistantDialog',
	components: {
		NcTextField,
		NcButton,
		NcModal,
	},
	props: {
		excalidrawAPI: {
			type: Object,
			required: true,
		},
	},
	emits: ['cancel', 'submit'],
	data() {
		return {
			assistantQuery: '',
			show: true,
			waitingForTask: false,
			generatedElements: {},
			mermaidError: false,
		}
	},
	mounted() {
		this.$nextTick(() => {
			this.$refs.assistantDialog.focus()
		})
	},
	methods: {
		t,
		createAssistantMetadata(extraData = {}) {
			return {
				aiGenerated: AI_GENERATED_TYPE,
				...extraData,
			}
		},
		getAssistantDisclosureText() {
			return t('whiteboard', 'Output is generated by AI. Make sure to always double-check.')
		},
		getDiagramDisclosureText() {
			return t('whiteboard', 'Diagram shown here is generated by AI. Make sure to always double-check.')
		},
		onCancel() {
			this.show = false
			this.$emit('cancel')
		},
		markAssistantGeneratedElements(elements) {
			return elements.map((element) => ({
				...element,
				customData: {
					...element.customData,
					...this.createAssistantMetadata(),
				},
			}))
		},
		normalizeAssistantElements(elements) {
			elements.forEach((element) => {
				if (element.label) {
					element.label.fontFamily = WHITEBOARD_DEFAULT_FONT_FAMILY
				}
				if (element.type === 'text') {
					element.fontFamily = WHITEBOARD_DEFAULT_FONT_FAMILY
				}
				element.roughness = 0
			})
		},
		measureDisclosureTextWidth(text) {
			if (typeof document === 'undefined') {
				return text.length * AI_DISCLOSURE_LABEL_FONT_SIZE * 0.55
			}

			const canvas = document.createElement('canvas')
			const context = canvas.getContext('2d')

			if (!context) {
				return text.length * AI_DISCLOSURE_LABEL_FONT_SIZE * 0.55
			}

			context.font = AI_DISCLOSURE_LABEL_FONT_STRING
			return context.measureText(text).width
		},
		splitDisclosureWord(word, maxWidth) {
			const segments = []
			let currentSegment = ''

			for (const character of word) {
				const nextSegment = `${currentSegment}${character}`

				if (currentSegment && this.measureDisclosureTextWidth(nextSegment) > maxWidth) {
					segments.push(currentSegment)
					currentSegment = character
					continue
				}

				currentSegment = nextSegment
			}

			if (currentSegment) {
				segments.push(currentSegment)
			}

			return segments
		},
		wrapDisclosureText(text, maxWidth) {
			const words = text.split(/\s+/).filter(Boolean)

			if (!words.length) {
				return text
			}

			const lines = []
			let currentLine = ''

			words.forEach((word) => {
				const segments = this.measureDisclosureTextWidth(word) > maxWidth
					? this.splitDisclosureWord(word, maxWidth)
					: [word]

				segments.forEach((segment, index) => {
					const nextLine = currentLine ? `${currentLine} ${segment}` : segment

					if (this.measureDisclosureTextWidth(nextLine) <= maxWidth) {
						currentLine = nextLine
					} else {
						if (currentLine) {
							lines.push(currentLine)
						}
						currentLine = segment
					}

					if (index < segments.length - 1 && currentLine) {
						lines.push(currentLine)
						currentLine = ''
					}
				})
			})

			if (currentLine) {
				lines.push(currentLine)
			}

			return lines.join('\n')
		},
		addAssistantDisclosureLabel(elements) {
			if (!elements.length) {
				return elements
			}

			const [minX, , maxX, maxY] = getCommonBounds(elements)
			const diagramWidth = maxX - minX
			const disclosureText = this.wrapDisclosureText(
				this.getDiagramDisclosureText(),
				Math.min(
					AI_DISCLOSURE_LABEL_MAX_WIDTH,
					Math.max(AI_DISCLOSURE_LABEL_MIN_WIDTH, diagramWidth * 0.8),
				),
			)
			const [disclosureElement] = convertToExcalidrawElements([{
				type: 'text',
				x: minX,
				y: maxY + AI_DISCLOSURE_LABEL_GAP,
				text: disclosureText,
				fontSize: AI_DISCLOSURE_LABEL_FONT_SIZE,
				fontFamily: AI_DISCLOSURE_LABEL_FONT_FAMILY,
				textAlign: 'center',
				backgroundColor: 'transparent',
				strokeColor: '#6b7280',
				opacity: 80,
				customData: this.createAssistantMetadata({
					aiDisclosureLabel: true,
				}),
			}], { regenerateIds: true })

			return [
				...elements,
				{
					...disclosureElement,
					x: minX + ((diagramWidth - disclosureElement.width) / 2),
					y: maxY + AI_DISCLOSURE_LABEL_GAP,
				},
			]
		},
		async getExcalidrawElements(taskResponse) {
			this.mermaidError = false

			const { elements, files } = await parseMermaidToExcalidraw(taskResponse, {
				fontFamily: WHITEBOARD_DEFAULT_FONT,
			})
			this.normalizeAssistantElements(elements)

			const generatedElements = this.markAssistantGeneratedElements(
				convertToExcalidrawElements(elements, { regenerateIds: true }),
			)
			return {
				elements: this.addAssistantDisclosureLabel(generatedElements),
				files,
			}
		},
		async onGetTask() {
			this.waitingForTask = true
			this.mermaidError = false

			try {
				const response = await ScheduleTask(this.assistantQuery)
				const taskResponse = response.data.ocs.data.task.output.output

				const res = await this.getExcalidrawElements(taskResponse)
				this.$emit('submit', res)
			} catch (error) {
				this.mermaidError = error || t('whiteboard', 'An error occurred while creating the diagram')
				console.error('Error generating diagram:', this.mermaidError)
			} finally {
				this.waitingForTask = false
			}
		},
	},
})

</script>

<template>
	<NcModal v-if="show"
		:can-close="true"
		size="normal"
		@close="onCancel">
		<div class="assistant-dialog">
			<div>
				<h2>
					{{ t('whiteboard', 'Generate diagram') }}
				</h2>
				<div class="assistant-disclosure">
					<span class="assistant-disclosure__badge">AI</span>
					<p class="assistant-disclosure__text">
						{{ getAssistantDisclosureText() }}
					</p>
				</div>
				<div v-if="mermaidError" class="mermaid-error">
					{{ t('whiteboard', 'Something went wrong, please try again') }}
				</div>
				<form @submit.prevent="onGetTask">
					<NcTextField ref="assistantDialog"
						v-model="assistantQuery"
						:label="t('whiteboard', 'Prompt to generate diagram')"
						:placeholder="t('whiteboard', 'Flowchart, sequence diagram…')"
						type="text"
						:disabled="waitingForTask" />
					<div class="dialog-buttons">
						<NcButton @click="onCancel">
							{{ t('whiteboard', 'Close') }}
						</NcButton>
						<NcButton :disabled="waitingForTask" type="submit">
							{{ waitingForTask ? t('whiteboard', 'Generating…') : t('whiteboard', 'Generate') }}
						</NcButton>
					</div>
				</form>
			</div>
		</div>
	</NcModal>
</template>
<style scoped lang="scss">
.loading-icon {
	padding: 30px;
}

h2 {
	text-align: center;
}

.assistant-dialog {
	display: flex;
	flex-direction: column;
	justify-content: space-evenly;
	overflow: hidden;

	form {
		padding-inline: 10px;
	}
}

.assistant-disclosure {
	display: flex;
	align-items: flex-start;
	gap: 10px;
	margin: 0 10px 14px;
	padding: 8px 10px;
	border: 1px solid transparent;
	border-radius: 6px;
	background:
		linear-gradient(var(--color-background-assistant), var(--color-background-assistant)) padding-box,
		var(--color-border-assistant) border-box;
	color: var(--color-main-text);
	font-size: var(--font-size-small);
	line-height: 1.35;
}

.assistant-disclosure__badge {
	flex: none;
	min-width: 28px;
	padding: 2px 6px;
	border-radius: 6px;
	background: var(--color-border-assistant);
	font-size: 11px;
	font-weight: 700;
	line-height: 1.4;
	text-align: center;
}

.assistant-disclosure__text {
	margin: 0;
	font-weight: 500;
}

.dialog-buttons {
	display: flex;
	justify-content: space-between;
	align-items: center;
	width: 100%;
	padding-block: 10px;
}

.mermaid-error {
	text-align: center;
	font-weight: bold;
}
</style>
